<?php
require_once '../includes/auth.php';
require_once '../config/database.php';
$pageTitle = 'Create Bill';
require_once '../includes/header.php';
?>
<form id="billForm" action="save.php" method="post" autocomplete="off">
  <section class="card"><div class="stepper"><span class="active">1. Patient</span><span>2. Medicines</span><span>3. Charges & payment</span></div>
  <fieldset id="tab1"><h1>Create patient bill</h1><div class="form-grid">
    <label>Invoice no.*<input name="invoice_no" type="number" min="1" required></label><label>Bill date*<input name="bill_date" type="date" value="<?= date('Y-m-d') ?>" required></label><label>Bill time*<input name="bill_time" type="time" value="<?= date('H:i') ?>" required></label>
  </div><h2>Patient information</h2><div class="form-grid">
    <label>Patient name*<input name="patient_name" required></label><label>Registration no.<input name="patient_registration_no"></label><label>UHID<input name="uhid"></label><label>Guardian name<input name="guardian_name"></label><label>Age<input name="age" placeholder="e.g. 28y / 2d"></label><label>Gender<select name="gender"><option value="">Select</option><option>Male</option><option>Female</option><option>Other</option></select></label><label>Mobile<input name="mobile" inputmode="tel"></label>
  </div><h2>Address</h2><div class="form-grid"><label>Village<input name="village"></label><label>Post office<input name="post_office"></label><label>Police station<input name="police_station"></label><label>District<input name="district"></label><label>Block<input name="block"></label><label>GP / Municipality<input name="gp_municipality"></label></div>
  <h2>Admission / discharge</h2><div class="form-grid"><label>Admission date<input name="admission_date" type="date"></label><label>Admission time<input name="admission_time" type="time"></label><label>Discharge date<input name="discharge_date" type="date"></label><label>Discharge time<input name="discharge_time" type="time"></label></div>
  <h2>Case & treatment</h2><div class="form-grid"><label>Case type<input name="case_type" list="caseTypeList" placeholder="Type or choose a case type"></label><label>Treated by doctor<input name="treated_by_doctor"></label><label>Reference doctor<input name="reference_doctor"></label><label>Diagnosis<textarea name="diagnosis_summary"></textarea></label><label>Treatment / operation<textarea name="treated_operations"></textarea></label><label>Baby details<textarea name="baby_details"></textarea></label></div>
  <datalist id="caseTypeList"><option value="Maternity"><option value="Baby / Pediatric"><option value="General"><option value="Surgery"><option value="Orthopedic"><option value="Gynecology"><option value="Other"></datalist>
  <div class="actions"><button type="button" data-next="tab2">Next: Medicines</button></div></fieldset>
  <fieldset id="tab2" hidden><h1>Medicine bill</h1><table id="medicineTable"><thead><tr><th>#</th><th>Qty</th><th>Medicine name</th><th>Batch no.</th><th>Expiry</th><th>Rate</th><th>Amount</th><th></th></tr></thead><tbody></tbody></table><button type="button" class="outline" id="addMedicine">+ Add medicine</button><p class="total-line">Total medicine bill <output id="medicineTotal">0.00</output></p><div class="actions"><button type="button" class="outline" data-back="tab1">Back</button><button type="button" data-next="tab3">Next: Charges & payment</button></div></fieldset>
  <fieldset id="tab3" hidden><h1>Other charges & payment</h1><table id="itemsTable"><thead><tr><th>#</th><th>Type</th><th>Particular</th><th>Rate</th><th>Qty</th><th>Amount</th><th></th></tr></thead><tbody></tbody></table><button type="button" class="outline" id="addItem">+ Add charge</button><div class="form-grid totals"><label>Medicine bill<input id="medicineBillAmount" readonly></label><label>Outside medicine<input name="outside_medicine_amount" id="outsideMedicineAmount" type="number" step=".01" min="0" value="0"></label><label>Outside medicine remarks<input name="outside_medicine_remarks"></label><label>Gross amount<input id="grossAmount" readonly></label><label>Discount<input name="discount" id="discount" type="number" step=".01" min="0" value="0"></label><label>Net amount<input id="netAmount" readonly></label><label>Paid amount<input name="paid_amount" id="paidAmount" type="number" step=".01" min="0" value="0"></label><label>Balance / due<input id="balanceAmount" readonly></label><label>Payment mode<select name="payment_mode"><option>Cash</option><option>UPI</option><option>Card</option><option>Bank Transfer</option><option>Other</option></select></label><label>Remarks<textarea name="remarks"></textarea></label></div><div class="actions"><button type="button" class="outline" data-back="tab2">Back</button><button name="action" value="save" type="submit">Save bill</button><button name="action" value="save_print" type="submit" class="success">Save & print</button></div></fieldset>
  </section>
</form><script src="../assets/js/billing.js"></script>
<?php require_once '../includes/footer.php'; ?>