CREATE DATABASE IF NOT EXISTS nursing_billing CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE nursing_billing;

CREATE TABLE users (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, username VARCHAR(50) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE settings (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, nursing_home_name VARCHAR(200) NOT NULL, establishment_type VARCHAR(200), registration_no VARCHAR(100), address TEXT, phone VARCHAR(100), email VARCHAR(150), logo VARCHAR(255), footer_text TEXT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE bills (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, bill_number VARCHAR(30) NOT NULL UNIQUE, invoice_no INT NOT NULL, bill_date DATE NOT NULL, bill_time TIME NOT NULL, patient_name VARCHAR(150) NOT NULL, patient_registration_no VARCHAR(100), uhid VARCHAR(100), guardian_name VARCHAR(150), age VARCHAR(20), gender VARCHAR(20), mobile VARCHAR(30), address TEXT, pin VARCHAR(20), village VARCHAR(150), post_office VARCHAR(150), police_station VARCHAR(150), district VARCHAR(150), block VARCHAR(150), gp_municipality VARCHAR(150), admission_date DATE, admission_time TIME, discharge_date DATE, discharge_time TIME, case_type VARCHAR(50), treated_by_doctor VARCHAR(150), reference_doctor VARCHAR(150), diagnosis_summary TEXT, treated_operations TEXT, baby_details TEXT, gross_amount DECIMAL(12,2) NOT NULL DEFAULT 0, discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0, net_amount DECIMAL(12,2) NOT NULL DEFAULT 0, paid_amount DECIMAL(12,2) NOT NULL DEFAULT 0, balance_amount DECIMAL(12,2) NOT NULL DEFAULT 0, payment_mode VARCHAR(30), outside_medicine_amount DECIMAL(12,2) NOT NULL DEFAULT 0, outside_medicine_remarks VARCHAR(255), gst_medicine_charges DECIMAL(12,2) NOT NULL DEFAULT 0, other_charges_amount DECIMAL(12,2) NOT NULL DEFAULT 0, consumables_charges DECIMAL(12,2) NOT NULL DEFAULT 0, remarks TEXT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE bill_diagnoses (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, bill_id INT UNSIGNED NOT NULL, diagnosis VARCHAR(255) NOT NULL, treatment TEXT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (bill_id) REFERENCES bills(id) ON DELETE CASCADE);
CREATE TABLE bill_items (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, bill_id INT UNSIGNED NOT NULL, item_type VARCHAR(50) NOT NULL DEFAULT 'Medicine', particular VARCHAR(255) NOT NULL, batch_no VARCHAR(100), expiry_date DATE, rate DECIMAL(12,2) NOT NULL DEFAULT 0, quantity DECIMAL(10,2) NOT NULL DEFAULT 1, amount DECIMAL(12,2) NOT NULL DEFAULT 0, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (bill_id) REFERENCES bills(id) ON DELETE CASCADE);
CREATE TABLE bill_summary_items (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, bill_id INT UNSIGNED NOT NULL, charge_name VARCHAR(255) NOT NULL, amount DECIMAL(12,2) NOT NULL DEFAULT 0, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (bill_id) REFERENCES bills(id) ON DELETE CASCADE);
CREATE TABLE discharge_medicines (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, medicine_name VARCHAR(255) NOT NULL UNIQUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
INSERT INTO settings (nursing_home_name, establishment_type, registration_no, address, phone, email) VALUES ('New Life Nursing Home', 'Clinical Establishment', '50339074', 'Uttar Darua, Darua, Contai, Purba Medinipur', '8918782920 / 6294264974', 'newlifenursinghome777@gmail.com');
-- Generate a secure hash with: php -r "echo password_hash('change-me', PASSWORD_DEFAULT), PHP_EOL;"
INSERT INTO users (username, password) VALUES ('admin', '$2y$10$//KvV1u2/l9J7woAmkP8lO0rlhR.gzdzfYbCvBXMTTk8Fd9yrCDBy');